import type { Payment } from "./types";

export const PAYMENTS: Payment[] = [
	{
		id: 1,
		amount: 100,
		date: "2026-01-23",
		title: "Big Star",
		description: "Sydneey Sweeney Jeans",
		category: "Clothes",
		categoryType: "want",
	},
	{
		id: 2,
		amount: 24,
		date: "2026-01-23",
		title: "Pills",
		description: "Sydneey Sweeney Jeans",
		category: "Drug Store",
		categoryType: "want",
	},
	{
		id: 3,
		amount: 24,
		date: "2026-01-23",
		title: "Concert",
		description: "Concert",
		category: "Entertainment",
		categoryType: "want",
	},
	{
		id: 4,
		amount: 124,
		date: "2026-01-23",
		title: "Santa Clause Box",
		description: "Concert",
		category: "Gifts",
		categoryType: "want",
	},
	{
		id: 5,
		amount: 124,
		date: "2026-01-23",
		title: "Pizzatopia",
		description: "Concert",
		category: "Going Out",
		categoryType: "want",
	},
	{
		id: 6,
		amount: 124,
		date: "2026-01-23",
		title: "Spain",
		description: "Concert",
		category: "Holiday",
		categoryType: "want",
	},
	{
		id: 7,
		amount: 124,
		date: "2026-01-24",
		title: "Zara Home",
		description: "Decor",
		category: "Home Decor",
		categoryType: "want",
	},
	{
		id: 8,
		amount: 624,
		date: "2026-01-24",
		title: "Biedronka",
		description: "Biedronka",
		category: "Hosuehold & Groceries",
		categoryType: "want",
	},
	{
		id: 9,
		amount: 3624,
		date: "2026-01-24",
		title: "Rent",
		description: "Rent",
		category: "Monthly Expenses",
		categoryType: "want",
	},
	{
		id: 10,
		amount: 2000,
		date: "2026-01-24",
		title: "XTB",
		description: "XTB",
		category: "Savings & Investments",
		categoryType: "want",
	},
	{
		id: 11,
		amount: 50,
		date: "2026-01-25",
		title: "McDonalds",
		description: "McDonalds",
		category: "Take out",
		categoryType: "want",
	},
	{
		id: 12,
		amount: 2250,
		date: "2026-01-25",
		title: "Rent",
		description: "Adrian",
		category: "Tattoo",
		categoryType: "want",
	},
	{
		id: 13,
		amount: 2,
		date: "2026-01-25",
		title: "Taxi",
		description: "Adrian",
		category: "Travel",
		categoryType: "want",
	},
	{
		id: 14,
		amount: 52,
		date: "2026-01-25",
		title: "GamePass",
		description: "Adrian",
		category: "Wasted Money",
		categoryType: "want",
	},
	{
		id: 15,
		amount: 52,
		date: "2026-01-25",
		title: "Cookies",
		description: "Adrian",
		category: "Treat",
		categoryType: "want",
	},
	{
		id: 16,
		amount: 2,
		date: "2026-01-28",
		title: "Taxi",
		description: "Adrian",
		category: "Travel",
		categoryType: "want",
	},
	{
		id: 17,
		amount: 52,
		date: "2026-01-28",
		title: "GamePass",
		description: "Adrian",
		category: "Wasted Money",
		categoryType: "want",
	},
	{
		id: 18,
		amount: 52,
		date: "2026-01-28",
		title: "Cookies",
		description: "Adrian",
		category: "Treat",
		categoryType: "want",
	},
	{
		id: 19,
		amount: 10000,
		date: "2026-01-28",
		title: "Income",
		description: "Salary",
		category: "Income",
		categoryType: "income",
	},
];
